[formatter.nix]
command = "nixfmt"
includes = ["*.nix", "**/*.nix"]

[formatter.python]
command = "ruff"
options = ["format"]
includes = ["*.py", "**/*.py"]

[formatter.shell]
command = "shfmt"
options = ["-ln", "bash", "-i", "2", "-w"]
includes = [
  "*.sh",
  "**/*.sh",
  "src/bin/nixos-upgrade",
  "src/lib/nixos-upgrade-activate",
]

[formatter.toml]
command = "taplo"
options = ["format"]
includes = ["*.toml", "**/*.toml"]

[formatter.markdown]
command = "prettier"
options = ["--write", "--parser", "markdown"]
includes = ["*.md", "**/*.md"]

[formatter.json]
command = "prettier"
options = ["--write", "--parser", "jsonc"]
includes = [
  "*.json",
  "*.jsonc",
  "**/*.json",
  "**/*.jsonc",
  ".zed/settings.json",
]
